const wordList = [
  { "spell": "a", "pingjia": "あ", "pianjia": "ア" },
  { "spell": "i", "pingjia": "い", "pianjia": "イ" },
  { "spell": "u", "pingjia": "う", "pianjia": "ウ" },
  { "spell": "e", "pingjia": "え", "pianjia": "エ" },
  { "spell": "o", "pingjia": "お", "pianjia": "オ" },
  { "spell": "ka", "pingjia": "か", "pianjia": "カ" },
  { "spell": "ki", "pingjia": "き", "pianjia": "キ" },
  { "spell": "ku", "pingjia": "く", "pianjia": "ク" },
  { "spell": "ke", "pingjia": "け", "pianjia": "ケ" },
  { "spell": "ko", "pingjia": "こ", "pianjia": "コ" },
  { "spell": "sa", "pingjia": "さ", "pianjia": "サ" },
  { "spell": "shi", "pingjia": "し", "pianjia": "シ" },
  { "spell": "su", "pingjia": "す", "pianjia": "ス" },
  { "spell": "se", "pingjia": "せ", "pianjia": "セ" },
  { "spell": "so", "pingjia": "そ", "pianjia": "ソ" },
  { "spell": "ta", "pingjia": "た", "pianjia": "タ" },
  { "spell": "chi", "pingjia": "ち", "pianjia": "チ" },
  { "spell": "tsu", "pingjia": "つ", "pianjia": "ツ" },
  { "spell": "te", "pingjia": "て", "pianjia": "テ" },
  { "spell": "to", "pingjia": "と", "pianjia": "ト" },
  { "spell": "na", "pingjia": "な", "pianjia": "ナ" },
  { "spell": "ni", "pingjia": "に", "pianjia": "ニ" },
  { "spell": "nu", "pingjia": "ぬ", "pianjia": "ヌ" },
  { "spell": "ne", "pingjia": "ね", "pianjia": "ネ" },
  { "spell": "no", "pingjia": "の", "pianjia": "ノ" },
  { "spell": "ha", "pingjia": "は", "pianjia": "ハ" },
  { "spell": "hi", "pingjia": "ひ", "pianjia": "ヒ" },
  { "spell": "fu", "pingjia": "ふ", "pianjia": "フ" },
  { "spell": "he", "pingjia": "へ", "pianjia": "ヘ" },
  { "spell": "ho", "pingjia": "ほ", "pianjia": "ホ" },
  { "spell": "ma", "pingjia": "ま", "pianjia": "マ" },
  { "spell": "mi", "pingjia": "み", "pianjia": "ミ" },
  { "spell": "mu", "pingjia": "む", "pianjia": "ム" },
  { "spell": "me", "pingjia": "め", "pianjia": "メ" },
  { "spell": "mo", "pingjia": "も", "pianjia": "モ" },
  { "spell": "ya", "pingjia": "や", "pianjia": "ヤ" },
  { "spell": "yu", "pingjia": "ゆ", "pianjia": "ユ" },
  { "spell": "yo", "pingjia": "よ", "pianjia": "ヨ" },
  { "spell": "ra", "pingjia": "ら", "pianjia": "ラ" },
  { "spell": "ri", "pingjia": "り", "pianjia": "リ" },
  { "spell": "ru", "pingjia": "る", "pianjia": "ル" },
  { "spell": "re", "pingjia": "れ", "pianjia": "レ" },
  { "spell": "ro", "pingjia": "ろ", "pianjia": "ロ" },
  { "spell": "wa", "pingjia": "わ", "pianjia": "ワ" },
  { "spell": "wo", "pingjia": "を", "pianjia": "ヲ" },
  { "spell": "nn", "pingjia": "ん", "pianjia": "ン" },
  { "spell": "ba", "pingjia": "ば", "pianjia": "バ" },
  { "spell": "bi", "pingjia": "び", "pianjia": "ビ" },
  { "spell": "bu", "pingjia": "ぶ", "pianjia": "ブ" },
  { "spell": "be", "pingjia": "べ", "pianjia": "ベ" },
  { "spell": "bo", "pingjia": "ぼ", "pianjia": "ボ" },
  { "spell": "ga", "pingjia": "が", "pianjia": "ガ" },
  { "spell": "gi", "pingjia": "ぎ", "pianjia": "ギ" },
  { "spell": "gu", "pingjia": "ぐ", "pianjia": "グ" },
  { "spell": "ge", "pingjia": "げ", "pianjia": "ゲ" },
  { "spell": "go", "pingjia": "ご", "pianjia": "ゴ" },
  { "spell": "za", "pingjia": "ざ", "pianjia": "ザ" },
  { "spell": "zi", "pingjia": "じ", "pianjia": "ジ" },
  { "spell": "zu", "pingjia": "ず", "pianjia": "ズ" },
  { "spell": "ze", "pingjia": "ぜ", "pianjia": "ゼ" },
  { "spell": "zo", "pingjia": "ぞ", "pianjia": "ゾ" },
  { "spell": "da", "pingjia": "だ", "pianjia": "ダ" },
  { "spell": "di", "pingjia": "ぢ", "pianjia": "ヂ" },
  { "spell": "du", "pingjia": "づ", "pianjia": "ヅ" },
  { "spell": "de", "pingjia": "で", "pianjia": "デ" },
  { "spell": "do", "pingjia": "ど", "pianjia": "ド" },
  { "spell": "pa", "pingjia": "ぱ", "pianjia": "パ" },
  { "spell": "pi", "pingjia": "ぴ", "pianjia": "ピ" },
  { "spell": "pu", "pingjia": "ぷ", "pianjia": "プ" },
  { "spell": "pe", "pingjia": "ぺ", "pianjia": "ペ" },
  { "spell": "po", "pingjia": "ぽ", "pianjia": "ポ" },
  { "spell": "kya", "pingjia": "きゃ", "pianjia": "キャ" },
  { "spell": "kyu", "pingjia": "きゅ", "pianjia": "キュ" },
  { "spell": "kyo", "pingjia": "きょ", "pianjia": "キョ" },
  { "spell": "sya", "pingjia": "しゃ", "pianjia": "シャ" },
  { "spell": "syu", "pingjia": "しゅ", "pianjia": "シュ" },
  { "spell": "syo", "pingjia": "しょ", "pianjia": "ショ" },
  { "spell": "cha", "pingjia": "ちゃ", "pianjia": "チャ" },
  { "spell": "chu", "pingjia": "ちゅ", "pianjia": "チュ" },
  { "spell": "cho", "pingjia": "ちょ", "pianjia": "チョ" },
  { "spell": "nya", "pingjia": "にゃ", "pianjia": "ニャ" },
  { "spell": "nyu", "pingjia": "にゅ", "pianjia": "ニュ" },
  { "spell": "nyo", "pingjia": "にょ", "pianjia": "ニョ" },
  { "spell": "hya", "pingjia": "ひゃ", "pianjia": "ヒャ" },
  { "spell": "hyu", "pingjia": "ひゅ", "pianjia": "ヒュ" },
  { "spell": "hyo", "pingjia": "ひょ", "pianjia": "ヒョ" },
  { "spell": "mya", "pingjia": "みゃ", "pianjia": "ミャ" },
  { "spell": "myu", "pingjia": "みゅ", "pianjia": "ミュ" },
  { "spell": "myo", "pingjia": "みょ", "pianjia": "ミョ" },
  { "spell": "rya", "pingjia": "りゃ", "pianjia": "リャ" },
  { "spell": "ryu", "pingjia": "りゅ", "pianjia": "リュ" },
  { "spell": "ryo", "pingjia": "りょ", "pianjia": "リョ" },
  { "spell": "bya", "pingjia": "びゃ", "pianjia": "ビャ" },
  { "spell": "byu", "pingjia": "びゅ", "pianjia": "ビュ" },
  { "spell": "byo", "pingjia": "びょ", "pianjia": "ビョ" },
  { "spell": "gya", "pingjia": "ぎゃ", "pianjia": "ギャ" },
  { "spell": "gyu", "pingjia": "ぎゅ", "pianjia": "ギュ" },
  { "spell": "gyo", "pingjia": "ぎょ", "pianjia": "ギョ" },
  { "spell": "zya", "pingjia": "じゃ", "pianjia": "ジャ" },
  { "spell": "zyu", "pingjia": "じゅ", "pianjia": "ジュ" },
  { "spell": "zyo", "pingjia": "じょ", "pianjia": "ジョ" },
  { "spell": "pya", "pingjia": "ぴゃ", "pianjia": "ピャ" },
  { "spell": "pyu", "pingjia": "ぴゅ", "pianjia": "ピュ" },
  { "spell": "pyo", "pingjia": "ぴょ", "pianjia": "ピョ" }
];

const pingjiaList = [
  "あ", "い", "う", "え", "お",
  "か", "き", "く", "け", "こ",
  "さ", "し", "す", "せ", "そ",
  "た", "ち", "つ", "て", "と",
  "な", "に", "ぬ", "ね", "の",
  "は", "ひ", "ふ", "へ", "ほ",
  "ま", "み", "む", "め", "も",
  "や", "ゆ", "よ",
  "ら", "り", "る", "れ", "ろ",
  "わ", "を", "ん",
  "ば", "び", "ぶ", "べ", "ぼ",
  "が", "ぎ", "ぐ", "げ", "ご",
  "ざ", "じ", "ず", "ぜ", "ぞ",
  "だ", "ぢ", "づ", "で", "ど",
  "ぱ", "ぴ", "ぷ", "ぺ", "ぽ",
  "きゃ", "きゅ", "きょ",
  "しゃ", "しゅ", "しょ",
  "ちゃ", "ちゅ", "ちょ",
  "にゃ", "にゅ", "にょ",
  "ひゃ", "ひゅ", "ひょ",
  "みゃ", "みゅ", "みょ",
  "りゃ", "りゅ", "りょ",
  "びゃ", "びゅ", "びょ",
  "ぎゃ", "ぎゅ", "ぎょ",
  "じゃ", "じゅ", "じょ",
  "ぴゃ", "ぴゅ", "ぴょ"
];

const pianjiaList = [
  "ア", "イ", "ウ", "エ", "オ",
  "カ", "キ", "ク", "ケ", "コ",
  "サ", "シ", "ス", "セ", "ソ",
  "タ", "チ", "ツ", "テ", "ト",
  "ナ", "ニ", "ヌ", "ネ", "ノ",
  "ハ", "ヒ", "フ", "ヘ", "ホ",
  "マ", "ミ", "ム", "メ", "モ",
  "ヤ", "ユ", "ヨ",
  "ラ", "リ", "ル", "レ", "ロ",
  "ワ", "ヲ", "ン",
  "バ", "ビ", "ブ", "ベ", "ボ",
  "ガ", "ギ", "グ", "ゲ", "ゴ",
  "ザ", "ジ", "ズ", "ゼ", "ゾ",
  "ダ", "ヂ", "ヅ", "デ", "ド",
  "パ", "ピ", "プ", "ペ", "ポ",
  "キャ", "キュ", "キョ",
  "シャ", "シュ", "ショ",
  "チャ", "チュ", "チョ",
  "ニャ", "ニュ", "ニョ",
  "ヒャ", "ヒュ", "ヒョ",
  "ミャ", "ミュ", "ミョ",
  "リャ", "リュ", "リョ",
  "ビャ", "ビュ", "ビョ",
  "ギャ", "ギュ", "ギョ",
  "ジャ", "ジュ", "ジョ",
  "ピャ", "ピュ", "ピョ"
];

const spellList = [
  "a", "i", "u", "e", "o",
  "ka", "ki", "ku", "ke", "ko",
  "sa", "shi", "su", "se", "so",
  "ta", "chi", "tsu", "te", "to",
  "na", "ni", "nu", "ne", "no",
  "ha", "hi", "fu", "he", "ho",
  "ma", "mi", "mu", "me", "mo",
  "ya", "yu", "yo",
  "ra", "ri", "ru", "re", "ro",
  "wa", "wo", "nn",
  "ba", "bi", "bu", "be", "bo",
  "ga", "gi", "gu", "ge", "go",
  "za", "zi", "zu", "ze", "zo",
  "da", "di", "du", "de", "do",
  "pa", "pi", "pu", "pe", "po",
  "kya", "kyu", "kyo",
  "sya", "syu", "syo",
  "cha", "chu", "cho",
  "nya", "nyu", "nyo",
  "hya", "hyu", "hyo",
  "mya", "myu", "myo",
  "rya", "ryu", "ryo",
  "bya", "byu", "byo",
  "gya", "gyu", "gyo",
  "zya", "zyu", "zyo",
  "pya", "pyu", "pyo"
];

const wordListLengthArr = [46, 71, 104];
const columnLengthArr = [5, 5, 5, 5, 5, 5, 5, 3, 5, 3, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3];
const colorList = [
  "#000000","#00003f","#00007f","#0000bf","#0000ff","#003f00","#003f3f","#003f7f","#003fbf",
  "#003fff","#007f00","#007f3f","#007f7f","#007fbf","#007fff","#00bf00","#00bf3f","#00bf7f",
  "#00bfbf","#00bfff","#00ff00","#00ff3f","#00ff7f","#00ffbf","#00ffff","#3f0000","#3f003f",
  "#3f007f","#3f00bf","#3f00ff","#3f3f00","#3f3f3f","#3f3f7f","#3f3fbf","#3f3fff","#3f7f00",
  "#3f7f3f","#3f7f7f","#3f7fbf","#3f7fff","#3fbf00","#3fbf3f","#3fbf7f","#3fbfbf","#3fbfff",
  "#3fff00","#3fff3f","#3fff7f","#3fffbf","#3fffff","#7f0000","#7f003f","#7f007f","#7f00bf",
  "#7f00ff","#7f3f00","#7f3f3f","#7f3f7f","#7f3fbf","#7f3fff","#7f7f00","#7f7f3f","#7f7f7f",
  "#7f7fbf","#7f7fff","#7fbf00","#7fbf3f","#7fbf7f","#7fbfbf","#7fbfff","#7fff00","#7fff3f",
  "#7fff7f","#7fffbf","#7fffff","#bf0000","#bf003f","#bf007f","#bf00bf","#bf00ff","#bf3f00",
  "#bf3f3f","#bf3f7f","#bf3fbf","#bf3fff","#bf7f00","#bf7f3f","#bf7f7f","#bf7fbf","#bf7fff",
  "#bfbf00","#bfbf3f","#bfbf7f","#bfbfbf","#bfbfff","#bfff00","#bfff3f","#bfff7f","#bfffbf",
  "#bfffff","#ff0000","#ff003f","#ff007f","#ff00bf","#ff00ff","#ff3f00","#ff3f3f","#ff3f7f",
  "#ff3fbf","#ff3fff","#ff7f00","#ff7f3f","#ff7f7f","#ff7fbf","#ff7fff","#ffbf00","#ffbf3f",
  "#ffbf7f","#ffbfbf","#ffbfff","#ffff00","#ffff3f","#ffff7f","#ffffbf","#ffffff"
];

module.exports = {
  wordList: wordList,
  spellList: spellList,
  pianjiaList: pianjiaList,
  pingjiaList: pingjiaList,
  wordListLengthArr: wordListLengthArr,
  columnLengthArr: columnLengthArr,
  colorList: colorList
};
